### ISSUE TITLE
Incorrect character used for italic text

### ISSUE THREAD

**Issue by derpynirvash** [fent/irc-colors.js#13]
In lib/irc-colors.js the italics character is defined as 
` italic    : '\x16'`

According to 
https://github.com/myano/jenni/wiki/IRC-String-Formatting#other-formatting
https://github.com/BlueWinds/pidgin-irc-format/blob/master/pidgin-irc-format.c
https://github.com/sopel-irc/sopel/wiki/IRC-colour-codes
http://git.kaashif.co.uk/weechat/file/src/plugins/irc/irc-color.h.html

\x16 is swap background and foreground colors ("reverse video") and \x1D is italics

Suggestion is to change line 24 in irc-colors.js from
`italic    : '\x16'`
to
`italic    : '\x1D'`

**Comment by derpynirvash** [comment]
Issue shows on,

mirc
hexchat
icechat
weechat (inside of screen inside of ssh inside of konsole)

**Comment by fent** [comment]
Yep, that can be done. :)

What do you think of Colloquy? I had previously tested `\x16` vs `\x1D` with regards to italics, and found that Colloquy would use `\x16` for italics. https://github.com/fent/irc-colors.js/issues/5#issuecomment-102419006

That was two years ago though. And it it's one client vs many, then we'd still choose what many use.
