### ISSUE TITLE
oftn-bot no color

### ISSUE THREAD

**Issue by dman777** [fent/irc-colors.js#4]
I can't seem to get my text colored in oftn-bot with this module. No errors. Not sure if I am doing something wrong. I made sure my channel mode as set without `c`.... `  [+npt]`. I tried:

```javascript
var c = require('irc-colors');
Bot.prototype.work = function(cx, text) {
    cx.channel.send_reply (cx.channel,
                c.red('this is text!'));
};
```

-------------------------------------------------------------

```javascript
require('irc-colors').global()
Bot.prototype.work = function(cx, text) {
    cx.channel.send_reply (cx.channel,
                'this is text!'.irc.red()));
};
```

**Comment by fent** [comment]
I'm not familiar with channel modes.

Are you able to see other colored text from others in the client?

**Comment by dman777** [comment]
Sorry, I found the issue...it was my end. `oftn-bot` requires a  `{ color: true }` parameter.
