### ISSUE TITLE
mIRC-style italics not stripped

### ISSUE THREAD

**Issue by pushrax** [fent/irc-colors.js#5]
`\x1d` is sometimes used for italics. ref: http://en.wikichip.org/wiki/irc/colors

It should probably be stripped to prevent bugs in dependents.

**Comment by fent** [comment]
not sure where I got `\x16` from, but they are stripped by printing the same character again.

I briefly tested with mibbit and couldn't get either to work for italics.

**Comment by fent** [comment]
Hello, any update?

**Comment by pushrax** [comment]
Up to you to decide if you want to address this, but basically I was seeing `\x1d` appearing in some messages produced by node-irc with `stripColors` on. Googling led me to determine that it this byte is sometimes used for italics.

**Comment by fent** [comment]
Just tested with [Colloquy](http://colloquy.info/), `\x16` did show the text as italics, but `x1d` didn't.

![](http://cl.ly/image/2u3g201I021g/Screen%20Shot%202015-05-15%20at%2010.45.06%20AM.png)
