### ISSUE TITLE
Certain strings can cause undesired output

### ISSUE THREAD

**Issue by HigherFive** [fent/irc-colors.js#6]
For example, `',1 cheeky hack'.irc.blue()` would return `'\u000312,1 cheeky hack\u0003'`.

I couldn't find a standard solution to this on the web, but using the zero width space character `\u200b` seems to do the trick.

**Comment by fent** [comment]
Using it before the string?

**Comment by HigherFive** [comment]
Yes, as in returning something like `'\u000312/u200b,1 cheeky hack\u0003'` when no bg color is specified.

**Comment by HigherFive** [comment]
Thanks for readily implementing this, but I was half-hoping for you to slap me and tell me of "the proper solution" to this. Adding a "non-standard" character like this doesn't seem like a good idea to me.

After considering it further, I think that any sanitizing of the input is better left up to the user.

**Comment by fent** [comment]
I seem to be easy to convince

other solution would be to add a transparent bg color, I didn't look into it though.

**Comment by rahatarmanahmed** [comment]
What was the "undesired output" in this scenario? `',1 cheeky hack'.irc.blue()` should return `'\u000312,1 cheeky hack\u0003'`, shouldn't it?
