### ISSUE TITLE
Remove addition of zero-width spaces

### ISSUE THREAD

**Issue by tobbez** [fent/irc-colors.js#9]
It puzzled me for a while why they turned up in sent IRC messages (since I also used them myself for other reasons).

I understand why they're added, but please use a different solution:
* Add codes that turns bold on and off right after the color code (e.g. `\x0312\x02\x02,1test` for the message `,1test`).
* Specify the background color as 99 (e.g. `\x0312,99,1test` for the message `,1test`).

Both of them would be consumed by color code parsing/stripping unlike the current state.

The first one (using bold) is likely to be compatible with more clients.

**Comment by fent** [comment]
I can see why the first option would be more widely supported, and briefly tested it on Mibbit. So I'll implement that shortly.
